### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, mkdir '~/AppData\Local\Temp\TabletopSimulator\Tab...

### ISSUE THREAD

**Issue by astranberg** [Berserk-Games/atom-tabletopsimulator-lua#125]
[Enter steps to reproduce:]

1. Open TTS.
2. "Get Lua Scripts" in Atom.
Atom and TTS are installed on separate drives. Is that the cause?

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 12.4.1

### Stack Trace

Uncaught Error: EPERM: operation not permitted, mkdir 'C:\Users\Adam\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua'

```
At C:\Users\Adam\.atom\packages\tabletopsimulator-lua\node_modules\mkdirp\index.js:91

Error: EPERM: operation not permitted, mkdir 'C:\Users\Adam\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua'
    at mkdirSync (fs.js:778:3)
    at Object.fs.mkdirSync (electron/js2c/asar.js:725:16)
    at Function.sync (/packages/tabletopsimulator-lua/node_modules/mkdirp/index.js:72:13)
    at FileHandler.create (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:419:12)
    at readFilesFromTTS (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:497:11)
    at handleMessage (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1897:7)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:2115:9)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17)
```

### Commands

```
     -0:19.9.0 tabletopsimulator-lua:openHelp (atom-pane.pane.active)
```

### Non-Core Packages

```
tabletopsimulator-lua 12.4.1 
```

**Comment by astranberg** [comment]
Solution: Run as admin.
