### ISSUE TITLE
Unexpected end of JSON input while parsing near '..."^1.7.0","jasmine-foc'

### ISSUE THREAD

**Issue by Ugleh** [Berserk-Games/atom-tabletopsimulator-lua#150]
Atom VS: 1.58.0
atom-tabletopsimulator-lua VS: 13.1.1
When attempting to install through the Packages menu I get this error:

37 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."^1.7.0","jasmine-foc'
37 verbose stack     at JSON.parse (<anonymous>)
37 verbose stack     at parseJson (C:\Users\troti\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
37 verbose stack     at C:\Users\troti\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
37 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by Ugleh** [comment]
For anyone that runs into this problem, I have fixed it. I have looked into many different reasons for this to happen, I talked to a few people and it was all the same. Inside Atom there is a portable node v12.14.1 and npm v6.14.13. You can find this out here
`C:\Users\{USER}\AppData\Local\atom\app-1.58.0\resources\app\apm\bin `

Anyways, I found that Atoms installation folder is located in your appdata. I didn't realize till so far in that there is another folder .atom located C:\Users\{USER}\.atom which stays even after uninstalling. You need to delete it after the uninstallation or simply delete the cache in it and try again.
