### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '~/AppData\Local\Temp\TabletopSimulato...

### ISSUE THREAD

**Issue by Gelature** [Berserk-Games/atom-tabletopsimulator-lua#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 1.1.9

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\Elias\AppData\Local\Temp\TabletopSimulator\Lua'

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir 'C:\Users\Elias\AppData\Local\Temp\TabletopSimulator\Lua'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Object.saveAndPlay (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:235:20)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:132:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:05.3.0 tabletopsimulator-lua:saveAndPlay (atom-pane.pane.active)
```

### Non-Core Packages

```
tabletopsimulator-lua 1.1.9 
```

**Comment by onelivesleft** [comment]
In Windows is there a folder 'C:\Users\Elias\AppData\Local\Temp\TabletopSimulator\Lua'?

If not, is there a folder 'C:\Users\Elias\AppData\Local\Temp\TabletopSimulator'?

For either not present, can you manually create them?
