### ISSUE TITLE
Cannot find module 'mkdrip'

### ISSUE THREAD

**Issue by olejika** [Berserk-Games/atom-tabletopsimulator-lua#53]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [atom-tabletopsimulator-lua-master](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.3.0

### Stack Trace

Failed to load the atom-tabletopsimulator-lua-master package

```
At Cannot find module 'mkdirp'

Error: Cannot find module 'mkdirp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:/ProgramData/Taras/atom/app-1.24.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:17:12)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:2443:4)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:2447:3)
    at Module.get_Module._compile (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package.js:782:33)
    at measure (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package.js:143:22)
    at Package.measure (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at Package.load (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package-manager.js:618:16)
    at config.transact (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (C:/ProgramData/Taras/atom/app-1.24.0/resources/app/src/atom-environment.js:818:27)
```

### Commands

```
```

### Non-Core Packages

```
tabletopsimulator-lua 10.3.0 
language-human-resource-machine 1.3.0 
teletype 0.9.0 
```

**Comment by onelivesleft** [comment]
How did you install the package? It should install the dependencies automatically.
