### ISSUE TITLE
Atom at linux can't work with TS runned in Wine

### ISSUE THREAD

**Issue by indvd00m** [Berserk-Games/atom-tabletopsimulator-lua#55]
Linux development with this atom package is not working (#3). Year ago I used atom in linux + TS in wine, and all worked fine, but now it failed too. Is this package work in native windows only?

[Enter steps to reproduce:]

1. Install Steam to wine and install Tabletop Simulator.
2. Install Atom to Linux and start it with tabletopsimulator-lua package.
3. Load game in TS.
4. Got error messages in Atom.

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Debian GNU/Linux
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.4.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\users\user\Мои документы//My Games//Tabletop Simulator//Saves\TS_AutoSave.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\users\user\Мои документы//My Games//Tabletop Simulator//Saves\TS_AutoSave.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.parseSavePath (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1419:26)
    at handleMessage (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1436:12)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1632:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -3:11.2.0 tabletopsimulator-lua:getObjects (a.stack-toggle)
```

### Non-Core Packages

```
tabletopsimulator-lua 10.4.0 
```

**Comment by onelivesleft** [comment]
`C:\users\user\Мои документы//My Games//Tabletop Simulator//Saves\TS_AutoSave.json` looks mangled: what is the legal path it should be?

**Comment by indvd00m** [comment]
Atom now can connect to TTS without Wine:

https://github.com/Berserk-Games/atom-tabletopsimulator-lua/issues/3#issuecomment-541245789

**Comment by azzco** [comment]
Still relevant in 2020, not all features work properly with the native linux client and running a wine layer can help with that but breaks functionality with this.
