### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by ukilop** [Berserk-Games/atom-tabletopsimulator-lua#56]
[Enter steps to reproduce:]

this is  was a auto generated error report from Atom, 
error occured while trying to save and play from atom.
i tried many things to get around this, i tried reloading the save file in tts.
i tried relaunching atom, i tried relaunching tts. every time game this error

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Education
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.4.0

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At C:\Users\-----\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1305

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1305:21)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1289:25)
    at TextEditor.save (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor.js:1148:38)
    at Object.module.exports.TabletopsimulatorLua.blocking_save (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:906:39)
    at Object.saveAndPlay (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:950:8)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:590:101)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:52.8.0 tabletopsimulator-lua:getObjects (atom-pane.pane.active)
     -0:50.6.0 core:select-all (input.hidden-input)
     -0:49.7.0 core:paste (input.hidden-input)
  3x -0:49.1.0 tabletopsimulator-lua:saveAndPlay (input.hidden-input)
     -0:07.6.0 editor:select-line (input.hidden-input)
     -0:05.9.0 tabletopsimulator-lua:getObjects (input.hidden-input)
     -0:04.0 tabletopsimulator-lua:saveAndPlay (input.hidden-input)
```

### Non-Core Packages

```
code-peek 1.4.21 
highlight-selected 0.13.1 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
styri-syntax 0.2.0 
tabletopsimulator-lua 10.4.0 
teletype 0.10.0 
```

**Comment by onelivesleft** [comment]
Should be fixed in or before v10.6.7
