### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Toni\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua\Block Square.cf25b5.ttslua'

### ISSUE THREAD

**Issue by Auoryus** [Berserk-Games/atom-tabletopsimulator-lua#59]
[Enter steps to reproduce:]

1. Start tts and atom in admin mode
2. Load scripts from tts with ctrl shift s
3. Make an object in tts and open script through tts and fill in in atom with a function
4. ctrl shift s and the error occurs + atom kinda sets itself in default mode opening only the welcome window

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: TONIPC
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.4.1

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Toni\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua\Block Square.cf25b5.ttslua'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at FileHandler.create (file:///C:/Users/Toni/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:230:14)
    at readFilesFromTTS (file:///C:/Users/Toni/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:329:11)
    at handleMessage (file:///C:/Users/Toni/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1455:7)
    at Socket.<anonymous> (file:///C:/Users/Toni/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1637:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

**Comment by amilth** [comment]
Also have this kind of problem. Closing and reopening Atom makes it possible to open the file again.
![skarmklipp](https://user-images.githubusercontent.com/37973669/38171227-9fd52d58-3595-11e8-9a5d-e8ed43fe29f3.PNG)

**Comment by Auoryus** [comment]
you can kind of fix it if you use a different version of atom, which installs on c: or d: and not in your users files

**Comment by onelivesleft** [comment]
Should be fixed before or in v10.6.7.  Comment if encountered again.
