### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by olejika** [Berserk-Games/atom-tabletopsimulator-lua#61]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.4.2

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At C:\ProgramData\Taras\atom\app-1.25.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1305

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1305:21)
    at TextBuffer.module.exports.TextBuffer.save (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1289:25)
    at TextEditor.save (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/src/text-editor.js:1148:38)
    at Object.module.exports.TabletopsimulatorLua.blocking_save (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:911:39)
    at Object.saveAndPlay (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:955:8)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:595:101)
    at CommandRegistry.handleCommandEvent (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/Taras/atom/app-1.25.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:03.4.0 core:paste (input.hidden-input)
     -0:55.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:55.5.0 snippets:expand (input.hidden-input)
     -0:55.5.0 editor:indent (input.hidden-input)
     -0:47.5.0 tabletopsimulator-lua:saveAndPlay (input.hidden-input)
     -0:35.1.0 core:select-all (input.hidden-input)
     -0:34.2.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
language-human-resource-machine 1.3.0 
tabletopsimulator-lua 10.4.2 
teletype 0.12.1 
```

**Comment by onelivesleft** [comment]
Should be fixed in or before v10.6.7
