### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, mkdir '~/AppData\Local\Temp\TabletopSimulator\Tab...

### ISSUE THREAD

**Issue by Andrew-Miner** [Berserk-Games/atom-tabletopsimulator-lua#98]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 11.1.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, mkdir 'C:\Users\Andrew\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua'

```
At C:\Users\Andrew\.atom\packages\tabletopsimulator-lua\node_modules\mkdirp\index.js:74

Error: EPERM: operation not permitted, mkdir 'C:\Users\Andrew\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:702:16)
    at Function.sync (/packages/tabletopsimulator-lua/node_modules/mkdirp/index.js:55:12)
    at FileHandler.create (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:342:12)
    at readFilesFromTTS (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:413:11)
    at handleMessage (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:1794:7)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:2012:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -0:57.9.0 core:backspace (input.hidden-input)
 20x -0:55.4.0 core:move-up (input.hidden-input)
  9x -0:54.1.0 core:move-left (input.hidden-input)
     -0:52.7.0 editor:newline (input.hidden-input)
     -0:52.2.0 core:move-up (input.hidden-input)
     -0:51.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:51.9.0 snippets:expand (input.hidden-input)
     -0:51.9.0 editor:indent (input.hidden-input)
  2x -0:50.5.0 core:backspace (input.hidden-input)
 24x -0:50 core:move-down (input.hidden-input)
  3x -0:48.2.0 core:move-up (input.hidden-input)
     -0:47 core:move-left (input.hidden-input)
     -0:34.2.0 core:cut (input.hidden-input)
     -0:29.2.0 core:paste (input.hidden-input)
     -0:26.8.0 tabletopsimulator-lua:saveAndPlay (input.hidden-input)
  2x -0:25 core:save (input.hidden-input)
```

### Non-Core Packages

```
tabletopsimulator-lua 11.1.0 
```

**Comment by kevin-d-omara** [comment]
Hi Andrew, I faced this issue in the past too. I think it only happens when you have the `C:\Users\Andrew\AppData\Local\Temp\TabletopSimulator\Tabletop Simulator Lua` folder open somewhere else. To resolve, just close that folder before running `saveAndPlay`.

I apologize if I'm incorrect. It's been a long time since I've faced this issue and I'm a little fuzzy on the solution.
